# Generated by Django 5.0.3 on 2024-04-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_category_name_alter_mymodel_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='basic.category', verbose_name='This is the help text'),
        ),
    ]
