# Generated by Django 5.0.3 on 2024-04-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_mymodel_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='kind',
            field=models.ForeignKey(help_text='This is the help text', on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='basic.category'),
        ),
    ]
